### ISSUE TITLE
Method identifier() not found on paragraphs item entity

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/paragraphs_table#1]
Simple fix in the `.module` would be to make this change:

```
-        $id = $field_paragraphs->identifier();
+        $id = $field_paragraphs->id();
```

**Comment by herbdool** [comment]
I've made a PR @oadaeh. I also delete a line not used: `$entityHost = $paragraph->hostEntity();` and fix syntax.

**Comment by oadaeh** [comment]
LGTM. Merged.
