### ISSUE TITLE
Do not display operations that aren't currently working

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/paragraphs_table#5]
The paragraph table display has a bunch of settings (duplicate, edit, delete) that don't do anything currently. I propose hiding these options for now and making them blank by default. Also there is an "+ Import" link that is always displayed because the setting is filled in by default but can't be cleared because it depends on a quick_data module being enabled. I propose that setting be blank by default too.

**Comment by herbdool** [comment]
@oadaeh I've got a PR to fix this. It also fixes the spelling on a couple variables.

**Comment by oadaeh** [comment]
@herbdool would you like to be a maintainer of this module? I don't actually use it. I only ported it because I ported its counterpart: [field_collection_table](https://github.com/backdrop-contrib/field_collection_table).

**Comment by herbdool** [comment]
@oadaeh sure I'll help maintain it.
